apiVersion: cost.kubethrift.io/v1
kind: CostQuota
metadata:
  labels:
    app.kubernetes.io/name: kubethrift
    app.kubernetes.io/managed-by: kustomize
  name: costquota-sample
spec:
  # TODO(user): Add fields here
